#!/bin/sh
set -e
if type systemctl >/dev/null 2>/dev/null; then
	OPTS=""

	if [ -n "$D" ]; then
		OPTS="--root=$D"
	fi

	if [ "disable" = "enable" ]; then
		for service in hostapd.service; do
			systemctl ${OPTS} enable "$service"
		done
	fi

	if [ -z "$D" ]; then
		systemctl daemon-reload
		systemctl preset hostapd.service

		if [ "disable" = "enable" ]; then
			systemctl --no-block restart hostapd.service
		fi
	fi
fi
