#!/bin/sh
set -e
if type systemctl >/dev/null 2>/dev/null; then
	OPTS=""

	if [ -n "$D" ]; then
		OPTS="--root=$D"
	fi

	if [ "disable" = "enable" ]; then
		for service in netdata.service; do
			systemctl ${OPTS} enable "$service"
		done
	fi

	if [ -z "$D" ]; then
		systemctl daemon-reload
		systemctl preset netdata.service

		if [ "disable" = "enable" ]; then
			systemctl --no-block restart netdata.service
		fi
	fi
fi
